// <auto-generated />
namespace MD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KeysDatabaseGenerated_Node : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeysDatabaseGenerated_Node));
        
        string IMigrationMetadata.Id
        {
            get { return "201810230658189_KeysDatabaseGenerated_Node"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
